name: Parser_HH CI Pipeline


on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest 

    env:
      POSTGRES_USER: ${{ secrets.DB_USER }}
      POSTGRES_PASSWORD: ${{ secrets.DB_PASS }}
      POSTGRES_DB: ${{ secrets.DB_NAME }}
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}

      APP_NAME: ${{ secrets.APP_NAME }}
      APP_EMAIL: ${{ secrets.APP_EMAIL }}

      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      TEST_ACCESS_TOKEN: ${{ secrets.TEST_ACCESS_TOKEN }}
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t inksne/parser_hh-back-image:latest .

      - name: Push Docker image to DockerHub
        run: |
          docker push inksne/parser_hh-back-image:latest


  test:
    runs-on: ubuntu-latest
    needs: build  
    

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Pull Docker image from DockerHub
        run: |
          docker pull inksne/parser_hh-back-image:latest

      - name: Run tests
        run: |
          docker run \
            -e POSTGRES_DB="${{ secrets.DB_NAME }}" \
            -e POSTGRES_USER="${{ secrets.DB_USER }}" \
            -e POSTGRES_PASSWORD="${{ secrets.DB_PASS }}" \
            -e POSTGRES_HOST="${{ secrets.POSTGRES_HOST }}" \
            -e APP_NAME="${{ secrets.APP_NAME }}" \
            -e APP_EMAIL="${{ secrets.APP_EMAIL }}" \
            -e ACCESS_TOKEN="${{ secrets.ACCESS_TOKEN }}" \
            -e TEST_ACCESS_TOKEN="${{ secrets.TEST_ACCESS_TOKEN }}" \
            --rm inksne/parser_hh-back-image pytest -v -s


  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: test  

  #   steps:
  #     - name: Check out repository
  #       uses: actions/checkout@v3

  #     - name: Set up Docker Compose
  #       run: |
  #         docker-compose up -d
